# Generated by Django 4.1.3 on 2025-01-29 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinationguidesapi', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at', 'region', 'country')},
        ),
    ]
